### ISSUE TITLE
Precompilation issues

### ISSUE THREAD

**Issue by chiefGui** [maxim/bootswatch-rails#66]
This happens:

> Sass::SyntaxError: Undefined variable: "$navbar-default-bg".
  (in /home/vagrant/local/ruby/gems/gems/bootswatch-rails-3.2.0/vendor/assets/stylesheets/bootswatch/amelia/_bootswatch.scss:16)

when I

`rake assets:precompile`

----

Why do am I getting this? Only happens on production.

**Comment by kalashnikovisme** [comment]
To solve this problem you should add to ```bootswatch/#{style_name}/_bootswatch.scss```  

```scss
@import 'variables'
``` 

as a first line

but than I had many problems, like:

* undefined mixin: box-shadow
* undefined mixin: gradient-vertical-three-colors

How fix this problem?

**Comment by westonganger** [comment]
@kalashnikovisme did you end up fixing your issue? I would love to know how

**Comment by westonganger** [comment]
This could have something to do with this issue. https://github.com/twbs/bootstrap-sass/issues/863
It seems like bootstrap-sass is not loading the variables either.

**Comment by westonganger** [comment]
the problem actually lies in config/intializers/assets.rb or config/environments/production.rb
```
Rails.application.config.assets.precompile += %w( * )
```
You shouldnt precompile all, instead selectively precompile additional assets as needed

**Comment by kalashnikovisme** [comment]
@westonganger no. I didn't solve my problem permanently. I've removed bootswatch-rails gem and add bootswatch css-js files to my project.

**Comment by chiefGui** [comment]
Guys, I no longer works with Rails/Bootswatch. Feel free to close this issue when you want. Thank you so far!

**Comment by ztvMark** [comment]
Si usas rails agregar al inicio de bootswatch.scss
@import "bootstrap";
tu css de bootswatch

y en tu aplication.scss
@import "variables";
@import "bootstrap";
@import "bootswatch";
