### ISSUE TITLE
Disable Google Fonts

### ISSUE THREAD

**Issue by kwent** [maxim/bootswatch-rails#7]
Hello,

There are any way to disable downloads of Google font by @import url ("http://fonts.googleapis.com[...]").

I'm running rails on a local computer which can no have internet access.

2 solutions : 
- Disable @import_url and replace by a basic system fonts.
- Make a static branch with google fonts already imported in the gem.

I already tried to vendorize the gem and comments import url but without success...

Could you help me ?

Best Regards

**Comment by TiagoCardoso1983** [comment]
Add the same issue, as we're using bootstrap in a private network whose proxy blocks calls to google. How can one cut this?
