### ISSUE TITLE
Problem with javascript.

### ISSUE THREAD

**Issue by fabdelgado** [maxim/bootswatch-rails#80]
There is a problem, not being included javascript files boostrap both as boostwatch

**Comment by maxim** [comment]
Could you please explain in more detail, and show some examples?

**Comment by latortuga** [comment]
https://github.com/thomaspark/bootswatch/tree/d2246acacb1c9ae45a70ab36f3ca980cded0c75b/assets/js

bootswatch includes javascript assets, the readme does not instruct and this repo does not appear to pull in these assets.

**Comment by theknightsky** [comment]
Simple add this line to your application.js file and it should work
`//= require bootstrap-sprockets`

**Comment by fabdelgado** [comment]
ok, @theknightsky thanks
