### ISSUE TITLE
Undefined Mixin Bug

### ISSUE THREAD

**Issue by joncalhoun** [maxim/bootswatch-rails#81]
Thanks for creating this gem!

Perhaps I am doing something wrong, but I keep running into an issue that is getting frustrating. I keep getting an `Undefined mixin 'gradient-vertical-three-colors'.` error. 

My first thought was that I need to import bootstrap/mixins, but if I do that the theme still doesn't appear to be correct (wrong color text in nav bar, etc), so I suspect something else is going on.

Any idea what I can do to try to resolve the issue? Happy to try to push a PR if we can figure out the underlying issue.

Here is my app.scss:
```scss
// Example using 'Cerulean' bootswatch

//Import bootstrap-sprockets
@import "bootstrap-sprockets";

// Import cerulean variables
@import "bootswatch/cerulean/variables";

// Then bootstrap itself
@import "bootstrap";

// And finally bootswatch style itself
@import "bootswatch/cerulean/bootswatch";
```

I am using ruby `2.2.2p95` and rails `4.2.3`, and my gemfile is shown below (important parts).

```
    bootstrap-sass (3.3.5.1)
      autoprefixer-rails (>= 5.0.0.1)
      sass (>= 3.3.0)

    bootswatch-rails (3.3.5)
      railties (>= 3.1)

    sass-rails (5.0.3)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (~> 1.1)
```

**Comment by emimarz** [comment]
me too +1

**Comment by Makapoxa** [comment]
Had this issue, solved it with adding 
```
@import "bootstrap/mixins";
```
before
```
@import "bootstrap"
```

**Comment by esbanarango** [comment]
Thanks @Makapoxa
